### ISSUE TITLE
Can't find swc-loader bindings on Windows(arm)

### ISSUE THREAD

**Issue by renzp94** [swc-project/swc-loader#78]
- "@swc/core": "^1.3.68",
- "swc-loader": "^0.2.3",
- "node": "v18.16.1"

mac/window(intel) is ok. window(arm) is error.

Reproduction warehouse：https://github.com/renzp94/swc-loader-bug-demo

`log`

`
ERROR in ./test.ts
Module build failed (from ./node_modules/swc-loader/src/index.js):
Error: Bindings not found.
    at Compiler.<anonymous> (C:\Users\mr.r\Desktop\swc-loader-bug-demo\node_modules\@swc\core\index.js:225:19)
    at Generator.next (<anonymous>)
    at C:\Users\mr.r\Desktop\swc-loader-bug-demo\node_modules\@swc\core\index.js:34:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\mr.r\Desktop\swc-loader-bug-demo\node_modules\@swc\core\index.js:30:12)
    at Compiler.transform (C:\Users\mr.r\Desktop\swc-loader-bug-demo\node_modules\@swc\core\index.js:202:16)
    at Object.transform (C:\Users\mr.r\Desktop\swc-loader-bug-demo\node_modules\@swc\core\index.js:344:21)
    at Object.<anonymous> (C:\Users\mr.r\Desktop\swc-loader-bug-demo\node_modules\swc-loader\src\index.js:86:21)
`

**Comment by kdy1** [comment]
https://www.npmjs.com/package/@swc/core-win32-arm64-msvc

Do `npm install` correctly, from the correct computer.

**Comment by renzp94** [comment]
> https://www.npmjs.com/package/@swc/core-win32-arm64-msvc
> 
> Do `npm install` correctly, from the correct computer.

Can I automatically export in the @ swc/core package? If I want to use SWC, do I need to install packages for all platforms to ensure that everyone can use them normally on different platforms?

**Comment by renzp94** [comment]
> 



> https://www.npmjs.com/package/@swc/core-win32-arm64-msvc
> 
> Do `npm install` correctly, from the correct computer.

I just tried it, but it still doesn't work. I installed Win11 in a virtual machine.

**Comment by kdy1** [comment]
You should install from the computer with the same cpu and arch

**Comment by renzp94** [comment]
Ok.Thanks.
